errorcodes = {
  "ERR_USERNAME_NOT_FOUND": 808, 
  "ERR_TAKEN_USERNAME": 809,
  "ERR_OVERFLOW_PLAYERS_NUMBER": 810, 
  "ERR_MATCH_OWNED": 811,
  "ERR_MATCH_NOT_OPEN": 812,
  "ERR_MATCH_NOT_EXIST": 813,
  "ERR_USER_NOT_IN_MATCH": 814,
  "ERR_NOT_MATCH_OWNER": 815,
  "ERR_MATCH_PASSWORD_INVALID": 816,
  "ERR_MATCH_NOT_READY": 817,
  "ERR_DECK_EMPTY": 818
}